### ISSUE TITLE
Diseño y explicación de la arquitectura solución.

### ISSUE THREAD

**Issue by omarmendozaaa** [omarmendozaaa/TF#12]
1. Diagrama general de la arquitectura.
2. Explicación de la arquitectura solución y de cada una de sus partes.

Observación: Docker, Cluster, Programación Distribuida y Microservicios.

**Criterios de Aceptación**
Mantener un mismo estilo en el diagrama.
Aprobación SCRUM TEAM

**Comment by pclertorarios** [comment]
Integración del diseño de la arquitectura y una breve descripción en el informe.

**Comment by ZandYand** [comment]
Se añadió la explicación de la arquitectura planteada.
