### ISSUE TITLE
Analizar paper.

### ISSUE THREAD

**Issue by omarmendozaaa** [omarmendozaaa/TF#8]
Se seleccionará dos papers por integrante. 
 Se creará un análisis
[Ejemplo Analisis Paper..pdf](https://github.com/omarmendozaaa/TF/files/7438893/Ejemplo.Analisis.Paper.pdf)
 similar a la Tarea Académica 1. 

**Criterios de aceptación:**
1. Calificación de Q1 - https://www.scimagojr.com/.
2. Actual - Desde el 2019 hasta la actualidad. 
3. Relacionado al Algoritmo de Regresión Lineal Simple.

**Comment by omarmendozaaa** [comment]
Primer Paper Omar Mendoza
**Título**: Hidden Markov Linear Regression Model and Its Parameter Estimation
**Ranking**: Q1 https://www.scimagojr.com/journalsearch.php?q=21100374601&tip=sid&clean=0
**Fecha de publicación**: 2020
**Enlace**: https://ieeexplore.ieee.org/document/9222161

Segundo Paper Omar Mendoza
**Título**: Distributed Online Linear Regressions
**Ranking**: Q1 https://www.scimagojr.com/journalsearch.php?q=21100338350&tip=sid&clean=0
**Fecha de publicación**: 2020
**Enlace**: https://ieeexplore.ieee.org/document/9216151

**Comment by MarcoPr4do** [comment]
Primer Paper 
Titulo: Estimation of ground-level PM2.5 concentration using MODIS AOD and corrected regression model over Beijing, China
Ranking: Q1 [https://www.scimagojr.com/journalsearch.php?q=10600153309&tip=sid&clean=0](url) 
Fecha de publicación: Octubre 13, 2020
Enlace: [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0240430](url)

**Comment by pclertorarios** [comment]
Primer Paper
Titulo:  SLA-Aware and Energy-Efficient VM Consolidation in Cloud Data Centers Using Robust Linear Regression Prediction Model
Ranking: Q1 https://www.scimagojr.com/journalsearch.php?q=21100374601&tip=sid&clean=0
Fecha de publicación: 10 October 2019
Enlace:  https://ieeexplore.ieee.org/abstract/document/8862140

**Comment by Fsnete7** [comment]
Primer Paper
Titulo: An Improved Forward Regression Variable Selection Algorithm for High-Dimensional Linear Regression Models
Ranking: Q1 https://www.scimagojr.com/journalsearch.php?q=21100374601&tip=sid&clean=0
Fecha de publicación: 15 July 2020
Enlace: https://ieeexplore.upc.elogim.com/document/9141247

Segundo Paper

Titulo: Data-Driven Power Flow Method Based on Exact Linear Regression Equations
Ranking: Q1 https://www.scimagojr.com/journalsearch.php?q=21100374601&tip=sid&clean=0
Fecha de publicación: 04 June 2021 
Enlace: https://ieeexplore.upc.elogim.com/document/9447250

**Comment by ZandYand** [comment]
Se seleccionaron 4 papers, pero estos pueden cambiar para la presentación final.
